.\"                                      Hey, EMACS: -*- nroff -*-
.\" We want the .URL macro
.mso www.tmac
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH FACTER 8 "June 17, 2011"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
facter \- Collect and display facts about the system
.SH SYNOPSIS
.B facter
.RI [ options ]
.RI [ fact ]
.RI ...
.SH DESCRIPTION
.B facter
collects and displays facts about the current system.
.PP
The library behind
.B Facter
is easy to expand, making
.B Facter
an easy way to collect information about a system from within the
shell or within Ruby.
.PP
If no facts are specifically asked for, then all facts will be
returned.

.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-\-yaml
Emit facts in YAML format.
.TP
.B \-\-json
Emit facts in JSON format.
.TP
.B \-\-puppet
Load the Puppet libraries, thus allowing Facter to load
Puppet-specific facts.
.TP
.B \-\-help
Show summary of options.
.TP
.B \-\-version
Show version of program.
.TP
.B \-\-debug
Enable debugging.
.TP
.B \-\-trace
Enable backtraces.
.TP
.B \-\-timing
Enable timing.

.SH EXAMPLES
.BI facter
Display a list of all facts
.TP
.BI facter \ kernel
Display the
.I kernel
fact
.SH SEE ALSO
.BR puppet (8),
.br
.URL http://www.puppetlabs.com/puppet/related-projects/facter/ "The facter homepage"
.br
.SH AUTHOR
facter was written by Luke Kanies
.PP
This manual page was written by Stig Sandbeck Mathisen <ssm@debian.org>,
for the Debian project (and may be used by others).
.SH COPYRIGHT
Facter is Copyright (c) 2011 Puppet Labs, Inc
.PP
Licensed under the Apache 2.0 license
